// src/components/ScrollIndicator.tsx
import React, { useState, useEffect } from "react";

export const ScrollIndicator: React.FC = () => {
  const [scrollPercentage, setScrollPercentage] = useState<number>(0);
  const updateScrollPercentage = () => {
    const scrollHeight: number = document.documentElement.scrollHeight - window.innerHeight;
    const percentage: number = (window.scrollY / scrollHeight) * 100;
    setScrollPercentage(percentage);
  };
  useEffect(() => {
    window.addEventListener("scroll", updateScrollPercentage);
    return () => {
      window.removeEventListener("scroll", updateScrollPercentage);
    };
  });
  return (
    <div
      className="fixed inset-0 h-1 bg-blue-500"
      style={{ width: `${scrollPercentage}%`, zIndex: "9999" }}
    ></div>
  );
};

// src/components/ScrollIndicator.vue
<template>
  <div
    class="bg-blue-500 h-1 fixed inset-0 z-[999]"
    :style="{ width: scrollPercentage + '%' }"
  ></div>
</template>

<script>
import { ref, onMounted, onUnmounted } from "vue";

export default {
  setup() {
    const scrollPercentage = ref(0);
    const updateScrollPercentage = () => {
      const scrollHeight = document.documentElement.scrollHeight - window.innerHeight;
      const percentage = (window.scrollY / scrollHeight) * 100;
      scrollPercentage.value = percentage;
    };
    onMounted(() => {
      window.addEventListener("scroll", updateScrollPercentage);
    });
    onUnmounted(() => {
      window.addEventListener("scroll", updateScrollPercentage);
    });
    return { scrollPercentage };
  },
};
</script>
