// src/components/global/scroll-indicator.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const WidthScrollBar = ref(0);

const ScrollPercentage = () => {
  const HeightScroll = document.documentElement.scrollHeight - window.innerHeight;
  const Percentage = (window.scrollY / HeightScroll) * 100;
  WidthScrollBar.value = Percentage;
};

onMounted(() => window.addEventListener("scroll", ScrollPercentage));
onUnmounted(() => window.removeEventListener("scroll", ScrollPercentage));
</script>

<template>
  <section
    class="fixed inset-0 top-24 z-50 h-1 bg-blue-500 lg:top-36"
    :style="{ width: WidthScrollBar + '%' }"
  ></section>
</template>

// src/common/scroll-indicator.jsx
import { useState } from "react";

export const ScrollIndicator = () => {
  const [scrollProgress, setScrollProgress] = useState(0);

  const ScrollPercentage = () => {
    const ScrollHeight = document.documentElement.scrollHeight - window.innerHeight;
    const Percentage = (window.scrollY / ScrollHeight) * 100;
    setScrollProgress(Percentage);
  };

  window.addEventListener("scroll", ScrollPercentage);

  return <section className="fixed inset-0 top-24 z-50 h-1 bg-blue-500 lg:top-36" style={{ width: `${scrollProgress}` + "%" }}></section>;
};
