// src/common/hamburger-menu.jsx
import { useEffect, useRef, useState } from "react";

export const HamburgerMenu = () => {
  const [open, setOpen] = useState(false);
  const hamburger = useRef(null);
  const menus = ["Inspirasi", "Penduduk", "Wisata"];

  useEffect(() => {
    const HandleOutside = (e) => (hamburger.current && !hamburger.current.contains(e.target)) ?? setOpen(false);
    document.addEventListener("click", HandleOutside);
    return () => document.removeEventListener("click", HandleOutside);
  }, []);

  return (
    <i className="fa-solid fa-bars flex cursor-pointer text-3xl text-gray-50 lg:hidden" onClick={() => setOpen(!open)}>
      {open &&
        <main ref={hamburger} className="absolute right-[10%] top-20 flex flex-col rounded-2xl bg-slate-50 p-0 text-base font-semibold text-gray-950 lg:hidden lg:text-lg">
          {menus.map((menu, i) =>
            <a key={i} href={`/${menu.toLowerCase()}`} className="mx-auto h-fit w-full py-5 text-center transition-all duration-300 ease-in-out first:rounded-t-2xl last:rounded-b-2xl hover:bg-slate-200">
              {menu}
            </a>  
          )}
        </main>
      }
    </i>
  );
};

// src/components/global/hamburger-menu.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const ShowHamburgerMenu = ref(false);
const Menus = ["Inspirasi", "Penduduk", "Wisata"];

const ToggleMenu = (e) => {
  if (document.querySelector("i").contains(e.target)) {
    ShowHamburgerMenu.value = !ShowHamburgerMenu.value;
  } else if (!document.querySelector("main").contains(e.target)) {
    ShowHamburgerMenu.value = false;
  }
};

onMounted(() => document.body.addEventListener("click", ToggleMenu));
onUnmounted(() => document.body.removeEventListener("click", ToggleMenu));
</script>

<template>
  <i class="fa-solid fa-bars flex cursor-pointer text-3xl text-gray-50"></i>
  <main v-if="ShowHamburgerMenu" class="absolute top-20 flex flex-col rounded-2xl bg-slate-50 p-0 text-base font-semibold text-gray-950 lg:top-32 lg:hidden lg:text-lg">
    <a
      v-for="menu in Menus"
      :href="`/${menu.toLowerCase()}`"
      :key="menu"
      class="mx-auto h-fit w-full py-5 text-center transition-all duration-300 ease-in-out first:rounded-t-2xl last:rounded-b-2xl hover:bg-slate-200"
    >
      {{ menu }}
    </a>
  </main>
</template>

<style scoped>
@media screen and (max-width: 3120px) {
  main {
    animation: fade-down 300ms ease-in-out;
  }
}
@media screen and (min-width: 1024px) {
  i {
    display: none;
  }
}
@keyframes fade-down {
  from {
    transform: translateY(-1.5rem);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}
</style>
